package archive2

// Message3 Performance/Maintenance Data
// see documentation RDA/RPG 3-44
type Message3 struct {
	_                                    uint16
	LoopBackTestStatus                   uint16
	T1OutputFrames                       uint32
	T1InputFrames                        uint32
	RouterMemoryUsed                     uint32
	RouterMemoryFree                     uint32
	RouterMemoryUtilization              uint16
	RouteToRPG                           uint16
	CSULossOfSignal                      uint32
	CSULossOfFrames                      uint32
	CSUYellowAlarms                      uint32 // Number of times Resource Availability Indication (RAI) (yellow) alarm received.
	CSUBlueAlarms                        uint32 // Number of times Alarm Indication Signal (AIS) (blue) alarm received
	CSU24hrErroredSeconds                uint32
	CSU24hrSeverelyErroredSeconds        uint32
	CSU24hrSeverelyErroredFramingSeconds uint32
	CSU24hrUnavailableSeconds            uint32
	CSU24hrControlledSlipSeconds         uint32
	CSU24hrPathCodingViolations          uint32
	CSU24hrLineErroredSeconds            uint32
	CSU24hrBurstyErroredSeconds          uint32
	CSU24hrDegradedMinutes               uint32
	_                                    uint32
	LANSwitchCPUUtilization              uint32
	LANSwitchMemory                      uint16
	_                                    uint16
	IFDRChassisTemp                      uint16
	IFDRFPGATemp                         uint16
	_                                    uint32
	GPSSats                              uint32
	_                                    uint32
	IPCStatus                            uint16
	CommandedChannelControl              uint16
	_                                    uint32
	_                                    uint16
	Polarization                         uint16
	AMEInternalTemp                      float32
	AMERecvModuleTemp                    float32
	AMEBITECALModuleTemp                 float32
	AMEPeltier                           uint16
	AMEPeltierStatus                     uint16
	AMEADConverterStatus                 uint16
	AMEState                             uint16
	AME33VPSVoltage                      float32
	AME5VPSVoltage                       float32
	AME65VPSVoltage                      float32
	AME15VPSVoltage                      float32
	AME48VPSVoltage                      float32
	AMESTALOPower                        float32
	PeltierCurrent                       float32
	ADCCalibrationRefVoltage             float32
	AMEMode                              uint16
	AMEPeltierMode                       uint16
	AMEPeltierInsideFanCurrent           float32
	AMEPeltierOutsideFanCurrent          float32
	HorzTRLimiterVoltage                 float32
	VertTRLimiterVoltage                 float32
	ADCCalibrationOffsetVoltage          float32
	ADCCalibrationGainCorrection         float32
	RCPStatus                            uint16
	RCPString                            [16]byte
	SPIPPowerButtons                     uint16
	_                                    uint32
	MasterPowerAdminLoad                 float32
	ExpansionPowerAdminLoad              float32
	_                                    [44]byte
	PS5VDC                               uint16
	PS15VDC                              uint16
	PS28VDC                              uint16
	PSn15VDC                             uint16
	PS45VDC                              uint16
	FilamentPSVoltage                    uint16
	VacuumPumpPSVoltage                  uint16
	FocusCoilPSVoltage                   uint16
	FilamentPS                           uint16
	KlystronWarmup                       uint16
	TransmitterAvail                     uint16
	WGSwitchPos                          uint16
	WGPFNTransferInterlock               uint16
	MaintenanceMode                      uint16
	MaintenanceRequired                  uint16
	PFNSwitchPosition                    uint16
	ModulatorOverload                    uint16
	ModulatorInvCurrent                  uint16
	ModulatorSwitchFail                  uint16
	MainPowerVoltage                     uint16
	ChargingSystemFail                   uint16
	InverseDiodeCurrent                  uint16
	TriggerAmp                           uint16
	CirculatorTemp                       uint16
	SpectrumFilterPressure               uint16
	WGARCVSWR                            uint16
	CabinetInterlock                     uint16
	CabinetAirTemp                       uint16
	CabinetAirflow                       uint16
	KlystronCurrent                      uint16
	KlystronFilamentCurrent              uint16
	KlystronVacionCurrent                uint16
	KlystronAirTemp                      uint16
	KlystronAirflow                      uint16
	ModulatorSwitchMaintenance           uint16
	PostChargeRegulatorMaintenance       uint16
	WGPressureHumidity                   uint16
	TransmitterOvervoltage               uint16
	TransmitterOvercurrent               uint16
	FocusCoilCurrent                     uint16
	FocusCoilAirflow                     uint16
	OilTemperature                       uint16
	PRFLimit                             uint16
	TransmitterOilLevel                  uint16
	TransmitterBatteryCharging           uint16
	HighVoltageStatus                    uint16
	TransmitterRecyclingSummary          uint16
	TransmitterInoperable                uint16
	TransmitterAirFilter                 uint16
	ZeroTestBit0                         uint16
	ZeroTestBit1                         uint16
	ZeroTestBit2                         uint16
	ZeroTestBit3                         uint16
	ZeroTestBit4                         uint16
	ZeroTestBit5                         uint16
	ZeroTestBit6                         uint16
	ZeroTestBit7                         uint16
	OneTestBit0                          uint16
	OneTestBit1                          uint16
	OneTestBit2                          uint16
	OneTestBit3                          uint16
	OneTestBit4                          uint16
	OneTestBit5                          uint16
	OneTestBit6                          uint16
	OneTestBit7                          uint16
	XMTRSPIPInterface                    uint16
	TransmitterSummaryStatus             uint16
	_                                    uint16
	TransmitterRFPowerSensor             float32
	HorizontalXMTRPeakPower              float32
	XMTRPeakPower                        float32
	VerticalXMTRPeakPower                float32
	XMTRRFAvgPower                       float32
	_                                    uint32
	XMTRRecycleCount                     uint32
	ReceiverBiasMeasurement              float32
	TransmitImbalance                    float32
	XMTRPowerMeterZero                   float32
	_                                    [8]byte
	ACUnit1CompressorShutoff             uint16
	ACUnit2CompressorShutoff             uint16
	GeneratorMaintenanceRequired         uint16
	GeneratorBatteryVoltage              uint16
	GeneratorEngine                      uint16
	GeneratorVoltFreq                    uint16
	PowerSource                          uint16
	TransitionalPowerSource              uint16
	GeneratorAutoRunOffSwitch            uint16
	AircraftHazardLighting               uint16
	_                                    [22]byte
	EquipmentShelterFireDetectionSystem  uint16
	EquipmentShelterFireSmoke            uint16
	GeneratorShelterFireSmoke            uint16
	UtilityVoltFreq                      uint16
	SiteSecurityAlarm                    uint16
	SecurityEquipment                    uint16
	SecuritySystem                       uint16
	ReceiverConnectedToAntenna           uint16
	RadomeHatch                          uint16
	ACUnit1FilterDirty                   uint16
	ACUnit2FilterDirty                   uint16
	EquipmentShelterTemp                 float32
	OutsideAmbientTemp                   float32
	TransmitterLeavingAirTemp            float32
	ACUnit1DischargeAirTemp              float32
	GeneratorShelterTemp                 float32
	RadomeAirTemp                        float32
	ACUnit2DischargeAirTemp              float32
	SPIPp15VPS                           float32
	SPIPn15VPS                           float32
	SPIP28VStatus                        uint16
	_                                    uint16
	SPIP5VPS                             float32
	ConvertedGeneratorFuelLevel          uint16
	_                                    [32]byte
	ElevationUpperDeadLimit              uint16
	Overvolatage150                      uint16
	Undervolatage150                     uint16
	ElevationServoAmpInhibit             uint16
	ElevationServoAmpOvertemp            uint16
	ElevationServoAmpShortCircuit        uint16
	ElevationMotorOvertemp               uint16
	ElevationStowPin                     uint16
	ElevationHousing5VPS                 uint16
	ElevationLowerDeadLimit              uint16
	ElevationUpperNormalLimit            uint16
	ElevationLowerNormalLimit            uint16
	ElevationEncoderLight                uint16
	ElevationGearboxOil                  uint16
	ElevationHandwheel                   uint16
	ElevationAmpPS                       uint16
	AzimuthServoAmpInhibit               uint16
	AzimuthServoAmpShortCircuit          uint16
	AzimuthServoAmpOvertemp              uint16
	AzimuthMotorOvertemp                 uint16
	AzimuthStowPin                       uint16
	AzimuthHousing5VPS                   uint16
	AzimuthEncoderLight                  uint16
	AzimuthGearboxOil                    uint16
	AzimuthBullGearboxOil                uint16
	AzimuthHandwheel                     uint16
	AzimuthServoAMPPS                    uint16
	Servo                                uint16
	PedestalInterlockSwitch              uint16
	_                                    [24]byte
	COHOClock                            uint16
	RFGeneratorFreqSelectOsc             uint16
	RFGeneratorRFSTALO                   uint16
	RFGeneratorPhaseShiftedCOHO          uint16
	Receiver9VpPS                        uint16
	Receiver5vpPS                        uint16
	Receiver18VpPS                       uint16
	Receiver9VnPS                        uint16
	SingleChanRDAIU5VpPS                 uint16
	_                                    uint16
	HorzShortPulseNoise                  float32
	HorzLongPulseNoise                   float32
	HorzNoiseTemp                        float32
	VertShortPulseNoise                  float32
	VertLongPulseNoise                   float32
	VertNoiseTemp                        float32
	HorzLinearty                         float32
	HorzDynamicRange                     float32
	HorzDeltadBZ                         float32
	VertDeltadBZ                         float32
	KDPeakMeasured                       float32
	_                                    uint32
	ShortPulseHorzdbz                    float32
	LongPulseHorzdbz                     float32
	VelocityProcessed                    uint16
	WidthProcessed                       uint16
	VelocityRFGen                        uint16
	WidthRFGen                           uint16
	HorzIO                               float32
	VertIO                               float32
	VertDynamicRange                     float32
	ShortPulseVertdbz                    float32
	LongPulseVertdbz                     float32
	_                                    uint32
	_                                    uint32
	HorzPowerSense                       float32
	VertPowerSense                       float32
	ZDRBias                              float32
	_                                    [12]byte
	ClutterSuppressionDelta              float32
	ClutterSuppressionUnfilteredPower    float32
	ClutterSuppressionFilteredPower      float32
	_                                    uint32
	_                                    uint32
	_                                    uint32
	_                                    uint32
	_                                    uint32
	VertLinearity                        float32
	_                                    [8]byte
	StateFileReadStatus                  uint16
	StateFileWriteStatus                 uint16
	BypassMapFileReadStatus              uint16
	BypassMapFileWriteStatus             uint16
	_                                    uint16
	_                                    uint16
	CurrentAdaptationFileReadStatus      uint16
	CurrentAdaptationFileWriteStatus     uint16
	CensorZoneFileReadStatus             uint16
	CensorZoneFileWriteStatus            uint16
	RemoteVCPFileReadStatus              uint16
	RemoteVCPFileWriteStatus             uint16
	BaselineAdaptationFileReadStatus     uint16
	ReadStatusPRFSets                    uint16
	ClutterFilterMapFileReadStatus       uint16
	ClutterFilterMapFileWriteStatus      uint16
	GeneralDiskIOError                   uint16
	RSPStatus                            uint8
	MotherboardTemp                      uint8
	CPU1Temp                             uint8
	CPU2Temp                             uint8
	CPU1FanSpeed                         uint16
	CPU2FanSpeed                         uint16
	RSPFan1Speed                         uint16
	RSPFan2Speed                         uint16
	RSPFan3Speed                         uint16
	_                                    [12]byte
	SPIPCommStatus                       uint16
	HCIComStatus                         uint16
	_                                    uint16
	SignalProcessorCommandStatus         uint16
	AMECommStatus                        uint16
	RMSLinkStatus                        uint16
	RPGLinkStatus                        uint16
	InterpanelLinkStatus                 uint16
	PerformanceCheckTime                 uint32
	_                                    [18]byte
	Version                              uint16 /// Version number for the performance data message
}
